In [2]:
# Dependencies
import pandas as pd
from pathlib import Path

In [3]:
# CSV files
dataset_one = Path("Datasets/10000_movies(1915-2023).csv")
dataset_two = Path("Datasets/top_1000_popular_movies_tmdb.csv")

In [4]:
# Convert to dataframes
one_df = pd.read_csv(dataset_one)
two_df = pd.read_csv(dataset_two, lineterminator='\n')

In [5]:
one_df

,Unnamed: 0,Movie Name,Year of Release,Run Time in minutes,Movie Rating,Votes,MetaScore,Gross,Genre,Certification,Director,Stars,Description
0,0,The Shawshank Redemption,1994,142,9.3,2804443,82.0,28340000.0,['Drama'],R,['Frank Darabont'],"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'...","['Over', 'the', 'course', 'of', 'several', 'ye..."
1,1,The Godfather,1972,175,9.2,1954174,100.0,134970000.0,"['Crime', ' Drama']",R,['Francis Ford Coppola'],"['Marlon Brando', 'Al Pacino', 'James Caan', '...","['Don', 'Vito', 'Corleone,', 'head', 'of', 'a'..."
2,2,Ramayana: The Legend of Prince Rama,1993,135,9.2,12995,NaN,NaN,"['Animation', ' Action', ' Adventure']",PG,"['Ram Mohan', 'Yûgô Sakô', 'Koichi Saski']","['Arun Govil', 'Nikhil Kapoor', 'Edie Mirman',...","['An', 'anime', 'adaptation', 'of', 'the', 'Hi..."
3,3,The Chaos Class,1975,87,9.2,42231,NaN,NaN,"['Comedy', ' Drama']",NaN,['Ertem Egilmez'],"['Kemal Sunal', 'Münir Özkul', 'Halit Akçatepe...","['Lazy,', 'uneducated', 'students', 'share', '..."
4,4,The Dark Knight,2008,152,9.0,2786129,84.0,534860000.0,"['Action', ' Crime', ' Drama']",PG-13,['Christopher Nolan'],"['Christian Bale', 'Heath Ledger', 'Aaron Eckh...","['When', 'the', 'menace', 'known', 'as', 'the'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Golmaal Again,2017,140,4.9,10183,NaN,1010000.0,"['Action', ' Comedy', ' Fantasy']",Not Rated,['Rohit Shetty'],"['Ajay Devgn', 'Arshad Warsi', 'Tabu', 'Shreya...","['The', 'gang', 'encounters', 'with', 'some', ..."
9996,9996,Not to Forget,2021,84,4.9,11191,NaN,NaN,['Drama'],NaN,['Valerio Zanoli'],"['Karen Grassle', 'Louis Gossett Jr.', ""Tatum ...","['After', 'a', 'lifetime', 'of', 'scams,', 'a'..."
9997,9997,Housefull 3,2016,140,4.9,10308,NaN,1160000.0,"['Action', ' Comedy', ' Romance']",Not Rated,"['Sajid', 'Farhad Samji']","['Akshay Kumar', 'Abhishek Bachchan', 'Riteish...","['A', 'father', ""doesn't"", 'want', 'his', 'thr..."
9998,9998,A.I. Rising,2018,85,4.9,11187,NaN,NaN,"['Drama', ' Romance', ' Sci-Fi']",R,['Lazar Bodroza'],"['Sebastian Cavazza', 'Stoya', 'Marusa Majer',...","['An', 'intimate', 'relationship', 'between', ..."
9999,9999,The Last Boy,2019,87,4.9,10324,NaN,NaN,"['Fantasy', ' Mystery', ' Sci-Fi']",NaN,['Perry Bhandal'],"['Luke Goss', 'Flynn Allen', 'Peter Guinness',...","['With', 'the', ""world's"", 'end', 'imminent,',..."

In [6]:
# Delete unneeded columns
del one_df["Unnamed: 0"]
del one_df["Stars"]
del one_df["Run Time in minutes"]
del one_df["Description"]
del one_df["MetaScore"]
one_df

,Movie Name,Year of Release,Movie Rating,Votes,Gross,Genre,Certification,Director
0,The Shawshank Redemption,1994,9.3,2804443,28340000.0,['Drama'],R,['Frank Darabont']
1,The Godfather,1972,9.2,1954174,134970000.0,"['Crime', ' Drama']",R,['Francis Ford Coppola']
2,Ramayana: The Legend of Prince Rama,1993,9.2,12995,NaN,"['Animation', ' Action', ' Adventure']",PG,"['Ram Mohan', 'Yûgô Sakô', 'Koichi Saski']"
3,The Chaos Class,1975,9.2,42231,NaN,"['Comedy', ' Drama']",NaN,['Ertem Egilmez']
4,The Dark Knight,2008,9.0,2786129,534860000.0,"['Action', ' Crime', ' Drama']",PG-13,['Christopher Nolan']
...,...,...,...,...,...,...,...,...
9995,Golmaal Again,2017,4.9,10183,1010000.0,"['Action', ' Comedy', ' Fantasy']",Not Rated,['Rohit Shetty']
9996,Not to Forget,2021,4.9,11191,NaN,['Drama'],NaN,['Valerio Zanoli']
9997,Housefull 3,2016,4.9,10308,1160000.0,"['Action', ' Comedy', ' Romance']",Not Rated,"['Sajid', 'Farhad Samji']"
9998,A.I. Rising,2018,4.9,11187,NaN,"['Drama', ' Romance', ' Sci-Fi']",R,['Lazar Bodroza']
9999,The Last Boy,2019,4.9,10324,NaN,"['Fantasy', ' Mystery', ' Sci-Fi']",NaN,['Perry Bhandal']

In [7]:
two_df

,Unnamed: 0,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
0,0,385687,Fast X,2023-05-17,"['Action', 'Crime', 'Thriller']",English,7.4,1347,8363.473,Over many missions and against impossible odds...,340000000,"['Universal Pictures', 'Original Film', 'One R...",652000000,142,The end of the road begins.
1,1,603692,John Wick: Chapter 4,2023-03-22,"['Action', 'Thriller', 'Crime']",English,7.9,2896,4210.313,"With the price on his head ever increasing, Jo...",90000000,"['Thunder Road', '87Eleven', 'Summit Entertain...",431769198,170,"No way back, one way out."
2,2,502356,The Super Mario Bros. Movie,2023-04-05,"['Animation', 'Family', 'Adventure', 'Fantasy'...",English,7.8,4628,3394.458,"While working underground to fix a water main,...",100000000,"['Universal Pictures', 'Illumination', 'Ninten...",1308766975,92,NaN
3,3,569094,Spider-Man: Across the Spider-Verse,2023-05-31,"['Action', 'Adventure', 'Animation', 'Science ...",English,8.8,1160,2859.047,"After reuniting with Gwen Stacy, Brooklyn’s fu...",100000000,"['Columbia Pictures', 'Sony Pictures Animation...",313522201,140,It's how you wear the mask that matters
4,4,536437,Hypnotic,2023-05-11,"['Mystery', 'Thriller', 'Science Fiction']",English,6.5,154,2654.854,A detective becomes entangled in a mystery inv...,70000000,"['Studio 8', 'Solstice Productions', 'Ingeniou...",0,94,Control is an illusion.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,33142,Vivah,2006-11-10,"['Romance', 'Drama']",Hindi,6.4,70,12.301,"Poonam, a traditionally brought-up young woman...",0,['Rajshri Productions'],4000000,175,Marriage isn't a game...
9996,9996,9442,Dead Men Don't Wear Plaid,1982-05-21,"['Comedy', 'Mystery']",English,6.6,324,12.301,Juliet Forrest is convinced that the reported ...,9000000,"['Universal Pictures', 'Aspen Film Society']",18196170,89,Laugh...or I’ll blow your lips off!
9997,9997,28774,Communion,1989-11-10,"['Drama', 'Horror', 'Science Fiction', 'Thrill...",English,5.3,147,12.300,A novelist's wife and son see him changed by a...,5000000,"['The Picture Property Company', 'Allied Visio...",1919653,103,The true story of one man's terrifying journey...
9998,9998,11121,Tess,1979-10-06,"['Drama', 'Romance']",English,7.0,283,12.300,A strong-willed peasant girl is sent by her fa...,12000000,"['Renn Productions', 'Timothy Burrill Producti...",20101247,186,She was born into a world where they called it...
9999,9999,272692,The Possession of Michael King,2014-08-14,['Horror'],English,6.1,346,12.297,The film tells the story of documentary filmma...,0,"['Quickfire Films', 'Gold Circle Films']",2405143,83,"If you invite it in, it will never let you go."

In [8]:
# Delete unneeded columns
del two_df["Unnamed: 0"]
del two_df["id"]
del two_df["tagline"]
del two_df["release_date"]
del two_df["original_language"]
del two_df["popularity"]
del two_df["overview"]
del two_df["runtime"]
two_df

,title,genres,vote_average,vote_count,budget,production_companies,revenue
0,Fast X,"['Action', 'Crime', 'Thriller']",7.4,1347,340000000,"['Universal Pictures', 'Original Film', 'One R...",652000000
1,John Wick: Chapter 4,"['Action', 'Thriller', 'Crime']",7.9,2896,90000000,"['Thunder Road', '87Eleven', 'Summit Entertain...",431769198
2,The Super Mario Bros. Movie,"['Animation', 'Family', 'Adventure', 'Fantasy'...",7.8,4628,100000000,"['Universal Pictures', 'Illumination', 'Ninten...",1308766975
3,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...",8.8,1160,100000000,"['Columbia Pictures', 'Sony Pictures Animation...",313522201
4,Hypnotic,"['Mystery', 'Thriller', 'Science Fiction']",6.5,154,70000000,"['Studio 8', 'Solstice Productions', 'Ingeniou...",0
...,...,...,...,...,...,...,...
9995,Vivah,"['Romance', 'Drama']",6.4,70,0,['Rajshri Productions'],4000000
9996,Dead Men Don't Wear Plaid,"['Comedy', 'Mystery']",6.6,324,9000000,"['Universal Pictures', 'Aspen Film Society']",18196170
9997,Communion,"['Drama', 'Horror', 'Science Fiction', 'Thrill...",5.3,147,5000000,"['The Picture Property Company', 'Allied Visio...",1919653
9998,Tess,"['Drama', 'Romance']",7.0,283,12000000,"['Renn Productions', 'Timothy Burrill Producti...",20101247
9999,The Possession of Michael King,['Horror'],6.1,346,0,"['Quickfire Films', 'Gold Circle Films']",2405143

In [9]:
# Rename columns for merging
two_df = two_df.rename(columns={"title": "Movie Name"})
two_df

,Movie Name,genres,vote_average,vote_count,budget,production_companies,revenue
0,Fast X,"['Action', 'Crime', 'Thriller']",7.4,1347,340000000,"['Universal Pictures', 'Original Film', 'One R...",652000000
1,John Wick: Chapter 4,"['Action', 'Thriller', 'Crime']",7.9,2896,90000000,"['Thunder Road', '87Eleven', 'Summit Entertain...",431769198
2,The Super Mario Bros. Movie,"['Animation', 'Family', 'Adventure', 'Fantasy'...",7.8,4628,100000000,"['Universal Pictures', 'Illumination', 'Ninten...",1308766975
3,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...",8.8,1160,100000000,"['Columbia Pictures', 'Sony Pictures Animation...",313522201
4,Hypnotic,"['Mystery', 'Thriller', 'Science Fiction']",6.5,154,70000000,"['Studio 8', 'Solstice Productions', 'Ingeniou...",0
...,...,...,...,...,...,...,...
9995,Vivah,"['Romance', 'Drama']",6.4,70,0,['Rajshri Productions'],4000000
9996,Dead Men Don't Wear Plaid,"['Comedy', 'Mystery']",6.6,324,9000000,"['Universal Pictures', 'Aspen Film Society']",18196170
9997,Communion,"['Drama', 'Horror', 'Science Fiction', 'Thrill...",5.3,147,5000000,"['The Picture Property Company', 'Allied Visio...",1919653
9998,Tess,"['Drama', 'Romance']",7.0,283,12000000,"['Renn Productions', 'Timothy Burrill Producti...",20101247
9999,The Possession of Michael King,['Horror'],6.1,346,0,"['Quickfire Films', 'Gold Circle Films']",2405143

In [10]:
merged_df = pd.merge(two_df, one_df, on="Movie Name", how="left")
merged_df

,Movie Name,genres,vote_average,vote_count,budget,production_companies,revenue,Year of Release,Movie Rating,Votes,Gross,Genre,Certification,Director
0,Fast X,"['Action', 'Crime', 'Thriller']",7.4,1347,340000000,"['Universal Pictures', 'Original Film', 'One R...",652000000,2023.0,5.8,97114.0,NaN,"['Action', ' Adventure', ' Crime']",PG-13,['Louis Leterrier']
1,John Wick: Chapter 4,"['Action', 'Thriller', 'Crime']",7.9,2896,90000000,"['Thunder Road', '87Eleven', 'Summit Entertain...",431769198,2023.0,7.8,281426.0,NaN,"['Action', ' Crime', ' Thriller']",R,['Chad Stahelski']
2,The Super Mario Bros. Movie,"['Animation', 'Family', 'Adventure', 'Fantasy'...",7.8,4628,100000000,"['Universal Pictures', 'Illumination', 'Ninten...",1308766975,2023.0,7.1,195626.0,NaN,"['Animation', ' Adventure', ' Comedy']",PG,"['Aaron Horvath', 'Michael Jelenic', 'Pierre L..."
3,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...",8.8,1160,100000000,"['Columbia Pictures', 'Sony Pictures Animation...",313522201,2023.0,8.7,270500.0,NaN,"['Animation', ' Action', ' Adventure']",PG,"['Joaquim Dos Santos', 'Kemp Powers', 'Justin ..."
4,Hypnotic,"['Mystery', 'Thriller', 'Science Fiction']",6.5,154,70000000,"['Studio 8', 'Solstice Productions', 'Ingeniou...",0,2023.0,5.5,22509.0,NaN,"['Action', ' Mystery', ' Thriller']",R,['Robert Rodriguez']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10544,Vivah,"['Romance', 'Drama']",6.4,70,0,['Rajshri Productions'],4000000,2006.0,6.6,10528.0,NaN,"['Drama', ' Musical', ' Romance']",Not Rated,['Sooraj R. Barjatya']
10545,Dead Men Don't Wear Plaid,"['Comedy', 'Mystery']",6.6,324,9000000,"['Universal Pictures', 'Aspen Film Society']",18196170,1982.0,6.8,23129.0,18200000.0,"['Comedy', ' Crime', ' Mystery']",PG,['Carl Reiner']
10546,Communion,"['Drama', 'Horror', 'Science Fiction', 'Thrill...",5.3,147,5000000,"['The Picture Property Company', 'Allied Visio...",1919653,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10547,Tess,"['Drama', 'Romance']",7.0,283,12000000,"['Renn Productions', 'Timothy Burrill Producti...",20101247,1979.0,7.3,17743.0,NaN,"['Drama', ' Romance']",PG,['Roman Polanski']
10548,The Possession of Michael King,['Horror'],6.1,346,0,"['Quickfire Films', 'Gold Circle Films']",2405143,2014.0,5.7,13034.0,NaN,['Horror'],R,['David Jung']

In [11]:
# Drop missing data
del merged_df["budget"]
clean_df = merged_df.dropna(how="any")
clean_df

,Movie Name,genres,vote_average,vote_count,production_companies,revenue,Year of Release,Movie Rating,Votes,Gross,Genre,Certification,Director
8,The Little Mermaid,"['Adventure', 'Family', 'Fantasy', 'Romance']",6.2,616,"['Walt Disney Pictures', 'Lucamar Productions'...",414000000,1989.0,7.6,283516.0,111540000.0,"['Animation', ' Adventure', ' Family']",G,"['Ron Clements', 'John Musker']"
10,Avatar: The Way of Water,"['Science Fiction', 'Adventure', 'Action']",7.7,8493,"['20th Century Studios', 'Lightstorm Entertain...",2320250281,2022.0,7.6,461810.0,659680000.0,"['Action', ' Adventure', ' Fantasy']",PG-13,['James Cameron']
19,The Three Musketeers,"['Action', 'Adventure']",5.4,25,[],0,1973.0,7.1,19599.0,22020000.0,"['Action', ' Adventure', ' Romance']",PG,['Richard Lester']
20,The Three Musketeers,"['Action', 'Adventure']",5.4,25,[],0,1993.0,6.4,57836.0,53900000.0,"['Action', ' Adventure', ' Romance']",PG,['Stephen Herek']
21,The Three Musketeers,"['Action', 'Adventure']",5.4,25,[],0,2011.0,5.7,110746.0,20380000.0,"['Action', ' Adventure', ' Fantasy']",PG-13,['Paul W.S. Anderson']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10536,Les Misérables,"['Crime', 'Drama', 'History', 'Romance']",7.2,526,['Columbia Pictures'],14096321,2012.0,7.5,340260.0,148810000.0,"['Drama', ' Musical', ' Romance']",PG-13,['Tom Hooper']
10537,Les Misérables,"['Crime', 'Drama', 'History', 'Romance']",7.2,526,['Columbia Pictures'],14096321,1998.0,7.4,42543.0,14100000.0,"['Crime', ' Drama', ' Romance']",PG-13,['Bille August']
10538,15 Minutes,"['Action', 'Crime', 'Thriller']",5.9,624,"['New Line Cinema', 'Industry Entertainment', ...",56359980,2001.0,6.1,51436.0,24400000.0,"['Action', ' Crime', ' Drama']",R,['John Herzfeld']
10539,Love & Basketball,"['Comedy', 'Drama', 'Romance']",7.5,383,['40 Acres and a Mule Filmworks'],27728118,2000.0,7.2,23318.0,27440000.0,"['Drama', ' Romance', ' Sport']",PG-13,['Gina Prince-Bythewood']
10545,Dead Men Don't Wear Plaid,"['Comedy', 'Mystery']",6.6,324,"['Universal Pictures', 'Aspen Film Society']",18196170,1982.0,6.8,23129.0,18200000.0,"['Comedy', ' Crime', ' Mystery']",PG,['Carl Reiner']

In [12]:
# Replace empty brackets
clean_df["production_companies"] = clean_df["production_companies"].replace({"[]": "*"})
clean_df.drop(clean_df[clean_df["production_companies"]=="*"].index)
clean_df

/var/folders/ry/_22269n950s4yfgx8rkg1p0m0000gn/T/ipykernel_65140/1712569316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df["production_companies"] = clean_df["production_companies"].replace({"[]": "*"})

,Movie Name,genres,vote_average,vote_count,production_companies,revenue,Year of Release,Movie Rating,Votes,Gross,Genre,Certification,Director
8,The Little Mermaid,"['Adventure', 'Family', 'Fantasy', 'Romance']",6.2,616,"['Walt Disney Pictures', 'Lucamar Productions'...",414000000,1989.0,7.6,283516.0,111540000.0,"['Animation', ' Adventure', ' Family']",G,"['Ron Clements', 'John Musker']"
10,Avatar: The Way of Water,"['Science Fiction', 'Adventure', 'Action']",7.7,8493,"['20th Century Studios', 'Lightstorm Entertain...",2320250281,2022.0,7.6,461810.0,659680000.0,"['Action', ' Adventure', ' Fantasy']",PG-13,['James Cameron']
19,The Three Musketeers,"['Action', 'Adventure']",5.4,25,*,0,1973.0,7.1,19599.0,22020000.0,"['Action', ' Adventure', ' Romance']",PG,['Richard Lester']
20,The Three Musketeers,"['Action', 'Adventure']",5.4,25,*,0,1993.0,6.4,57836.0,53900000.0,"['Action', ' Adventure', ' Romance']",PG,['Stephen Herek']
21,The Three Musketeers,"['Action', 'Adventure']",5.4,25,*,0,2011.0,5.7,110746.0,20380000.0,"['Action', ' Adventure', ' Fantasy']",PG-13,['Paul W.S. Anderson']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10536,Les Misérables,"['Crime', 'Drama', 'History', 'Romance']",7.2,526,['Columbia Pictures'],14096321,2012.0,7.5,340260.0,148810000.0,"['Drama', ' Musical', ' Romance']",PG-13,['Tom Hooper']
10537,Les Misérables,"['Crime', 'Drama', 'History', 'Romance']",7.2,526,['Columbia Pictures'],14096321,1998.0,7.4,42543.0,14100000.0,"['Crime', ' Drama', ' Romance']",PG-13,['Bille August']
10538,15 Minutes,"['Action', 'Crime', 'Thriller']",5.9,624,"['New Line Cinema', 'Industry Entertainment', ...",56359980,2001.0,6.1,51436.0,24400000.0,"['Action', ' Crime', ' Drama']",R,['John Herzfeld']
10539,Love & Basketball,"['Comedy', 'Drama', 'Romance']",7.5,383,['40 Acres and a Mule Filmworks'],27728118,2000.0,7.2,23318.0,27440000.0,"['Drama', ' Romance', ' Sport']",PG-13,['Gina Prince-Bythewood']
10545,Dead Men Don't Wear Plaid,"['Comedy', 'Mystery']",6.6,324,"['Universal Pictures', 'Aspen Film Society']",18196170,1982.0,6.8,23129.0,18200000.0,"['Comedy', ' Crime', ' Mystery']",PG,['Carl Reiner']

In [13]:
clean_df = clean_df.rename(columns={"vote_average": "Vote Average",
                                   "vote_count": "Vote Count",
                                   "production_companies": "Production Companies",
                                   "revenue": "Revenue"})

clean_df

,Movie Name,genres,vote_average,vote_count,production_companies,revenue,Year of Release,Movie Rating,Votes,Gross,Genre,Certification,Director
8,The Little Mermaid,"['Adventure', 'Family', 'Fantasy', 'Romance']",6.2,616,"['Walt Disney Pictures', 'Lucamar Productions'...",414000000,1989.0,7.6,283516.0,111540000.0,"['Animation', ' Adventure', ' Family']",G,"['Ron Clements', 'John Musker']"
10,Avatar: The Way of Water,"['Science Fiction', 'Adventure', 'Action']",7.7,8493,"['20th Century Studios', 'Lightstorm Entertain...",2320250281,2022.0,7.6,461810.0,659680000.0,"['Action', ' Adventure', ' Fantasy']",PG-13,['James Cameron']
19,The Three Musketeers,"['Action', 'Adventure']",5.4,25,*,0,1973.0,7.1,19599.0,22020000.0,"['Action', ' Adventure', ' Romance']",PG,['Richard Lester']
23,Mother's Day,"['Thriller', 'Drama', 'Action']",6.0,94,['Akson Studio'],0,2016.0,5.6,38894.0,32460000.0,"['Comedy', ' Drama', ' Romance']",PG-13,['Garry Marshall']
29,Spider-Man: Into the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...",8.4,13081,"['Columbia Pictures', 'Lord Miller', 'Pascal P...",375464627,2018.0,8.4,632177.0,190240000.0,"['Animation', ' Action', ' Adventure']",PG,"['Bob Persichetti', 'Peter Ramsey', 'Rodney Ro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10532,The Mark of Zorro,"['Action', 'Adventure', 'Drama', 'Romance']",7.1,174,['20th Century Fox'],0,1940.0,7.5,10674.0,4360000.0,"['Action', ' Adventure', ' Family']",Approved,['Rouben Mamoulian']
10534,54,"['Drama', 'Music']",5.8,422,"['Dollface', 'Redeemable Features', 'FilmColon...",16757163,1998.0,5.9,34130.0,16570000.0,"['Drama', ' Music']",R,['Mark Christopher']
10538,15 Minutes,"['Action', 'Crime', 'Thriller']",5.9,624,"['New Line Cinema', 'Industry Entertainment', ...",56359980,2001.0,6.1,51436.0,24400000.0,"['Action', ' Crime', ' Drama']",R,['John Herzfeld']
10539,Love & Basketball,"['Comedy', 'Drama', 'Romance']",7.5,383,['40 Acres and a Mule Filmworks'],27728118,2000.0,7.2,23318.0,27440000.0,"['Drama', ' Romance', ' Sport']",PG-13,['Gina Prince-Bythewood']
10545,Dead Men Don't Wear Plaid,"['Comedy', 'Mystery']",6.6,324,"['Universal Pictures', 'Aspen Film Society']",18196170,1982.0,6.8,23129.0,18200000.0,"['Comedy', ' Crime', ' Mystery']",PG,['Carl Reiner']

In [14]:
clean_df = clean_df.rename(columns={"vote_average": "Vote Average",
                                   "vote_count": "Vote Count",
                                   "production_companies": "Production Companies",
                                   "revenue": "Revenue"})
del clean_df["Genres"]
clean_df

KeyError: 'Genres'

In [ ]:
# Save csv file
clean_df.to_csv("Datasets/clean_data.csv", index=False, header=True)

In [15]:
clean_data = Path("Datasets/clean_data.csv")
clean_data_df = pd.read_csv(clean_data)
clean_data_df

,Movie Name,Vote Average,Vote Count,Production Companies,Revenue,Year of Release,Movie Rating,Votes,Gross,Genre,Certification,Director
0,The Little Mermaid,6.2,616,"['Walt Disney Pictures', 'Lucamar Productions'...",414000000,1989.0,7.6,283516.0,111540000.0,"['Animation', ' Adventure', ' Family']",G,"['Ron Clements', 'John Musker']"
1,Avatar: The Way of Water,7.7,8493,"['20th Century Studios', 'Lightstorm Entertain...",2320250281,2022.0,7.6,461810.0,659680000.0,"['Action', ' Adventure', ' Fantasy']",PG-13,['James Cameron']
2,The Three Musketeers,5.4,25,*,0,1973.0,7.1,19599.0,22020000.0,"['Action', ' Adventure', ' Romance']",PG,['Richard Lester']
3,Mother's Day,6.0,94,['Akson Studio'],0,2016.0,5.6,38894.0,32460000.0,"['Comedy', ' Drama', ' Romance']",PG-13,['Garry Marshall']
4,Spider-Man: Into the Spider-Verse,8.4,13081,"['Columbia Pictures', 'Lord Miller', 'Pascal P...",375464627,2018.0,8.4,632177.0,190240000.0,"['Animation', ' Action', ' Adventure']",PG,"['Bob Persichetti', 'Peter Ramsey', 'Rodney Ro..."
...,...,...,...,...,...,...,...,...,...,...,...,...
4195,The Mark of Zorro,7.1,174,['20th Century Fox'],0,1940.0,7.5,10674.0,4360000.0,"['Action', ' Adventure', ' Family']",Approved,['Rouben Mamoulian']
4196,54,5.8,422,"['Dollface', 'Redeemable Features', 'FilmColon...",16757163,1998.0,5.9,34130.0,16570000.0,"['Drama', ' Music']",R,['Mark Christopher']
4197,15 Minutes,5.9,624,"['New Line Cinema', 'Industry Entertainment', ...",56359980,2001.0,6.1,51436.0,24400000.0,"['Action', ' Crime', ' Drama']",R,['John Herzfeld']
4198,Love & Basketball,7.5,383,['40 Acres and a Mule Filmworks'],27728118,2000.0,7.2,23318.0,27440000.0,"['Drama', ' Romance', ' Sport']",PG-13,['Gina Prince-Bythewood']
4199,Dead Men Don't Wear Plaid,6.6,324,"['Universal Pictures', 'Aspen Film Society']",18196170,1982.0,6.8,23129.0,18200000.0,"['Comedy', ' Crime', ' Mystery']",PG,['Carl Reiner']

In [16]:
filtered_df = clean_data_df.loc[(clean_data_df['Year of Release'] > 2009)
                     & (clean_data_df['Year of Release'] < 2020)]
filtered_df

,Movie Name,Vote Average,Vote Count,Production Companies,Revenue,Year of Release,Movie Rating,Votes,Gross,Genre,Certification,Director
3,Mother's Day,6.0,94,['Akson Studio'],0,2016.0,5.6,38894.0,32460000.0,"['Comedy', ' Drama', ' Romance']",PG-13,['Garry Marshall']
4,Spider-Man: Into the Spider-Verse,8.4,13081,"['Columbia Pictures', 'Lord Miller', 'Pascal P...",375464627,2018.0,8.4,632177.0,190240000.0,"['Animation', ' Action', ' Adventure']",PG,"['Bob Persichetti', 'Peter Ramsey', 'Rodney Ro..."
8,Transformers: Age of Extinction,5.9,7359,"['di Bonaventura Pictures', 'Tom DeSanto/Don M...",1104054072,2014.0,5.6,326960.0,245440000.0,"['Action', ' Adventure', ' Sci-Fi']",PG-13,['Michael Bay']
12,Transformers: The Last Knight,6.1,5548,"['Paramount', 'di Bonaventura Pictures', 'Ian ...",605425157,2017.0,5.2,164230.0,130170000.0,"['Action', ' Adventure', ' Sci-Fi']",PG-13,['Michael Bay']
20,Guardians of the Galaxy Vol. 2,7.6,19898,['Marvel Studios'],863756051,2017.0,7.6,736895.0,389810000.0,"['Action', ' Adventure', ' Comedy']",PG-13,['James Gunn']
...,...,...,...,...,...,...,...,...,...,...,...,...
4185,The Butler,7.3,2692,"['Follow Through Productions', 'Salamander Pic...",115922175,2013.0,7.2,118325.0,116630000.0,"['Biography', ' Drama']",PG-13,['Lee Daniels']
4186,High-Rise,5.7,1038,"['HanWay Films', 'SCOPE Pictures', 'Recorded P...",346472,2015.0,5.5,44402.0,340000.0,"['Drama', ' Sci-Fi']",R,['Ben Wheatley']
4189,The Birth of a Nation,6.1,468,['Epoch Film Co.'],11000000,2016.0,6.5,21628.0,15860000.0,"['Biography', ' Drama', ' History']",R,['Nate Parker']
4190,Little Boy,7.2,485,"['Santa Fé Films', 'Metanoia Films']",6485961,2015.0,7.3,23885.0,6420000.0,"['Drama', ' History', ' War']",PG-13,['Alejandro Monteverde']
4191,Happy End,6.6,53,"['Myung Films', 'CJ Entertainment']",0,2017.0,6.6,16507.0,300000.0,['Drama'],R,['Michael Haneke']

In [17]:
# Save filtered csv file
filtered_df.to_csv("Datasets/filtered_data.csv", index=False, header=True)